from __future__ import annotations

from aitest_runtime.durable_core import RuntimeError


class R41Error(RuntimeError):
    """Fail-closed R4.1 contract, aggregate, and replay error."""


R41_SCHEMA_INVALID = "R4_1_SCHEMA_INVALID"
R41_EVENT_INVALID = "R4_1_EVENT_INVALID"
R41_COMMAND_INVALID = "R4_1_COMMAND_INVALID"
R41_MISSION_INVALID = "R4_1_MISSION_INVALID"
R41_IDENTITY_CONFLICT = "R4_1_IDENTITY_CONFLICT"
R41_IMMUTABLE_CONFLICT = "R4_1_IMMUTABLE_CONFLICT"
R41_REFERENCE_INVALID = "R4_1_REFERENCE_INVALID"
R41_DIGEST_MISMATCH = "R4_1_DIGEST_MISMATCH"
R41_SUPERSESSION_INVALID = "R4_1_SUPERSESSION_INVALID"
R41_EVENT_NOT_OWNED = "R4_1_EVENT_NOT_OWNED"
