from __future__ import annotations

from aitest_runtime.durable_core import RuntimeError


class R44Error(RuntimeError):
    """Fail-closed R4.4 contract error."""


NOT_FOUND = "NOT_FOUND"
CONFLICT = "CONFLICT"
DUPLICATE = "DUPLICATE"
IDEMPOTENT_REPLAY = "IDEMPOTENT_REPLAY"
FIX_DETECTION_NOT_READY = "FIX_DETECTION_NOT_READY"
VALIDATION_SCOPE_MISMATCH = "VALIDATION_SCOPE_MISMATCH"
CASE_NOT_APPROVED = "CASE_NOT_APPROVED"
CASE_VERSION_CONFLICT = "CASE_VERSION_CONFLICT"
ORACLE_NOT_APPROVED = "ORACLE_NOT_APPROVED"
ORACLE_VERSION_CONFLICT = "ORACLE_VERSION_CONFLICT"
EXECUTION_BINDING_MISSING = "EXECUTION_BINDING_MISSING"
EXECUTION_BLOCKED = "EXECUTION_BLOCKED"
HUMAN_GATE_REQUIRED = "HUMAN_GATE_REQUIRED"
RESULT_INCOMPLETE = "RESULT_INCOMPLETE"
RESULT_CONFLICT = "RESULT_CONFLICT"
REGRESSION_SELECTION_INCOMPLETE = "REGRESSION_SELECTION_INCOMPLETE"
REGRESSION_BLOCKED = "REGRESSION_BLOCKED"
SUFFICIENCY_HANDOFF_FAILED = "SUFFICIENCY_HANDOFF_FAILED"
ARCHITECTURE_BOUNDARY_VIOLATION = "ARCHITECTURE_BOUNDARY_VIOLATION"
UNKNOWN_EVENT = "UNKNOWN_EVENT"
UNKNOWN_SCHEMA = "UNKNOWN_SCHEMA"


__all__ = [
    "R44Error", "NOT_FOUND", "CONFLICT", "DUPLICATE", "IDEMPOTENT_REPLAY",
    "FIX_DETECTION_NOT_READY", "VALIDATION_SCOPE_MISMATCH", "CASE_NOT_APPROVED",
    "CASE_VERSION_CONFLICT", "ORACLE_NOT_APPROVED", "ORACLE_VERSION_CONFLICT",
    "EXECUTION_BINDING_MISSING", "EXECUTION_BLOCKED", "HUMAN_GATE_REQUIRED",
    "RESULT_INCOMPLETE", "RESULT_CONFLICT", "REGRESSION_SELECTION_INCOMPLETE",
    "REGRESSION_BLOCKED", "SUFFICIENCY_HANDOFF_FAILED", "ARCHITECTURE_BOUNDARY_VIOLATION",
    "UNKNOWN_EVENT", "UNKNOWN_SCHEMA",
]
