"""R4.7 legacy reconciliation and rebuildable operational projections boundary."""

from .contracts import (
    EXTENSION_ID,
    EXTENSION_VERSION,
    SCHEMA_VERSION,
    ActiveWriterState,
    AssessmentOutcome,
    CanonicalAuthority,
    CanonicalHandoffLinkage,
    ContentRelation,
    DecisionKind,
    ExistingKnowledgeReconciliation,
    HandoffKind,
    HandoffState,
    IdentityRelation,
    LegacyCanonicalMapping,
    LegacySourceAdapter,
    LegacySourceObservation,
    LegacySourceObservationInput,
    MappingEvidence,
    MappingStatus,
    ReconciliationAssessment,
    ReconciliationCase,
    ReconciliationDecision,
    ReconciliationReceipt,
    RebuildCheckpoint,
    ReceiptStatus,
    ResolutionStatus,
    R47OperationResult,
    R47State,
    ShadowTruthStatus,
    ScopeRelation,
    SourceAvailability,
    SourceFamily,
    SourceFreshness,
    SourceSelector,
    SourceValueState,
    CurrentReconciliationResolution,
)
from .canonical_handoff_bridge import R47CanonicalHandoffBridge
from .errors import R47ContractError, R47ErrorCode
from .service import R47ApplicationService, compose_r4_7_runtime
from .source_adapters import (
    LegacyArtifactReferenceAdapter,
    LegacyKnowledgeTeachingAdapter,
    LegacyProjectTruthAdapter,
    LegacyRuntimeQualityAdapter,
    LegacySkillMetadataAdapter,
)


__all__ = [
    "EXTENSION_ID",
    "EXTENSION_VERSION",
    "SCHEMA_VERSION",
    "R47ApplicationService",
    "R47CanonicalHandoffBridge",
    "R47OperationResult",
    "R47State",
    "compose_r4_7_runtime",
    "R47ErrorCode",
    "R47ContractError",
    "SourceSelector",
    "SourceFamily",
    "SourceValueState",
    "SourceAvailability",
    "SourceFreshness",
    "ActiveWriterState",
    "AssessmentOutcome",
    "IdentityRelation",
    "ScopeRelation",
    "ContentRelation",
    "MappingStatus",
    "MappingEvidence",
    "CanonicalAuthority",
    "DecisionKind",
    "ReceiptStatus",
    "HandoffState",
    "HandoffKind",
    "ResolutionStatus",
    "ShadowTruthStatus",
    "ExistingKnowledgeReconciliation",
    "ReconciliationCase",
    "LegacySourceObservationInput",
    "LegacySourceObservation",
    "ReconciliationAssessment",
    "LegacyCanonicalMapping",
    "ReconciliationDecision",
    "CanonicalHandoffLinkage",
    "ReconciliationReceipt",
    "RebuildCheckpoint",
    "CurrentReconciliationResolution",
    "LegacySourceAdapter",
    "LegacyKnowledgeTeachingAdapter",
    "LegacySkillMetadataAdapter",
    "LegacyProjectTruthAdapter",
    "LegacyRuntimeQualityAdapter",
    "LegacyArtifactReferenceAdapter",
]
