from __future__ import annotations

from aitest_runtime.durable_core.contracts import RuntimeError


NOT_FOUND = "NOT_FOUND"
CONFLICT = "CONFLICT"
DUPLICATE = "DUPLICATE"
IDEMPOTENT_REPLAY = "IDEMPOTENT_REPLAY"
R3_CONFIRMATION_INVALID = "R3_CONFIRMATION_INVALID"
R3_ASSESSMENT_DIGEST_CONFLICT = "R3_ASSESSMENT_DIGEST_CONFLICT"
FIX_LINK_INVALID = "FIX_LINK_INVALID"
FIX_SOURCE_UNAVAILABLE = "FIX_SOURCE_UNAVAILABLE"
FIX_SOURCE_STALE = "FIX_SOURCE_STALE"
FIX_DETECTION_INCONCLUSIVE = "FIX_DETECTION_INCONCLUSIVE"
FIX_DETECTION_CONFLICT = "FIX_DETECTION_CONFLICT"
SCOPE_MISMATCH = "SCOPE_MISMATCH"
ARCHITECTURE_BOUNDARY_VIOLATION = "ARCHITECTURE_BOUNDARY_VIOLATION"


class R43Error(RuntimeError):
    """R4.3 typed failure; durable_core remains the runtime error authority."""


__all__ = [
    "R43Error", "NOT_FOUND", "CONFLICT", "DUPLICATE", "IDEMPOTENT_REPLAY", "R3_CONFIRMATION_INVALID",
    "R3_ASSESSMENT_DIGEST_CONFLICT", "FIX_LINK_INVALID", "FIX_SOURCE_UNAVAILABLE", "FIX_SOURCE_STALE",
    "FIX_DETECTION_INCONCLUSIVE", "FIX_DETECTION_CONFLICT", "SCOPE_MISMATCH", "ARCHITECTURE_BOUNDARY_VIOLATION",
]
