"""R3.E1 durable, scope-owned Knowledge substrate extension."""

from .contracts import (
    ALLOWED_TRANSITIONS,
    ARCHITECTURE_BASELINE_REF,
    COMMAND_TYPES,
    DEFAULT_RETRIEVAL_STATUSES,
    ENDPOINT_TYPES,
    EVENT_TYPES,
    EXTENSION_ID,
    FRESHNESS_RESULTS,
    KNOWLEDGE_STATUSES,
    RELATION_SEMANTICS,
    SOURCE_CATEGORIES,
    CONFLICT_STATUSES,
    KnowledgeConflict,
    KnowledgeEndpointRef,
    KnowledgeFact,
    KnowledgeFreshness,
    KnowledgeRelation,
    KnowledgeScopeIdentity,
    KnowledgeSourceRef,
    KnowledgeVersion,
    R3E1Error,
    R3E1State,
    RECORD_CONFLICT,
    RECORD_FRESHNESS,
    RECORD_RELATION,
    REGISTER_VERSION,
    TRANSITION_LIFECYCLE,
    validate_transition,
)
from .extension import r3_e1_extension
from .service import R3E1ApplicationService, R3E1OperationResult
from .retrieval import (
    HARD_MAX_BYTES,
    HARD_MAX_ITEMS,
    KnowledgeRetrievalAdapter,
    KnowledgeRetrievalRequest,
    KnowledgeRetrievalResult,
    anchor_digest_for,
    build_r31_anchor,
)
from .context import BoundedSessionHandoff, bounded_session_handoff, build_context_request
from .vertical_slice import VerticalSliceCheck, VerticalSliceClosure, execute_vertical_slice

__all__ = [
    "ALLOWED_TRANSITIONS",
    "ARCHITECTURE_BASELINE_REF",
    "COMMAND_TYPES",
    "CONFLICT_STATUSES",
    "DEFAULT_RETRIEVAL_STATUSES",
    "ENDPOINT_TYPES",
    "EVENT_TYPES",
    "EXTENSION_ID",
    "FRESHNESS_RESULTS",
    "KNOWLEDGE_STATUSES",
    "RELATION_SEMANTICS",
    "SOURCE_CATEGORIES",
    "KnowledgeConflict",
    "KnowledgeEndpointRef",
    "KnowledgeFact",
    "KnowledgeFreshness",
    "KnowledgeRelation",
    "KnowledgeScopeIdentity",
    "KnowledgeSourceRef",
    "KnowledgeVersion",
    "KnowledgeRetrievalAdapter",
    "KnowledgeRetrievalRequest",
    "KnowledgeRetrievalResult",
    "R3E1ApplicationService",
    "R3E1Error",
    "R3E1OperationResult",
    "R3E1State",
    "RECORD_CONFLICT",
    "RECORD_FRESHNESS",
    "RECORD_RELATION",
    "REGISTER_VERSION",
    "TRANSITION_LIFECYCLE",
    "r3_e1_extension",
    "HARD_MAX_BYTES",
    "HARD_MAX_ITEMS",
    "BoundedSessionHandoff",
    "VerticalSliceCheck",
    "VerticalSliceClosure",
    "anchor_digest_for",
    "build_context_request",
    "build_r31_anchor",
    "bounded_session_handoff",
    "execute_vertical_slice",
    "validate_transition",
]
