from __future__ import annotations

TERMINAL_GOAL_STATUSES = frozenset({
    "SATISFIED",
    "COMPLETED_WITH_ACCEPTED_GAP",
    "BLOCKED",
    "CANCELLED",
    "STOPPED",
})

LEGAL_GOAL_TRANSITIONS = {
    "PROPOSED": frozenset({"PROPOSED", "ACTIVE", "CANCELLED", "STOPPED"}),
    "ACTIVE": frozenset({"ACTIVE", "EXECUTING", "MEASURING", "REPLANNING", "WAITING_HUMAN", "WAITING_COVERAGE_REFRESH", "WAITING_ENVIRONMENT", "WAITING_APPROVAL", "SATISFIED", "COMPLETED_WITH_ACCEPTED_GAP", "BLOCKED", "CANCELLED", "STOPPED"}),
    "EXECUTING": frozenset({"EXECUTING", "MEASURING", "REPLANNING", "WAITING_HUMAN", "WAITING_COVERAGE_REFRESH", "WAITING_ENVIRONMENT", "WAITING_APPROVAL", "SATISFIED", "COMPLETED_WITH_ACCEPTED_GAP", "BLOCKED", "CANCELLED", "STOPPED"}),
    "MEASURING": frozenset({"MEASURING", "REPLANNING", "WAITING_COVERAGE_REFRESH", "WAITING_ENVIRONMENT", "WAITING_APPROVAL", "SATISFIED", "COMPLETED_WITH_ACCEPTED_GAP", "BLOCKED", "CANCELLED", "STOPPED"}),
    "REPLANNING": frozenset({"REPLANNING", "EXECUTING", "MEASURING", "WAITING_HUMAN", "WAITING_COVERAGE_REFRESH", "WAITING_ENVIRONMENT", "WAITING_APPROVAL", "SATISFIED", "COMPLETED_WITH_ACCEPTED_GAP", "BLOCKED", "CANCELLED", "STOPPED"}),
    "WAITING_HUMAN": frozenset({"WAITING_HUMAN", "EXECUTING", "MEASURING", "REPLANNING", "BLOCKED", "CANCELLED", "STOPPED"}),
    "WAITING_COVERAGE_REFRESH": frozenset({"WAITING_COVERAGE_REFRESH", "MEASURING", "REPLANNING", "BLOCKED", "CANCELLED", "STOPPED"}),
    "WAITING_ENVIRONMENT": frozenset({"WAITING_ENVIRONMENT", "EXECUTING", "REPLANNING", "BLOCKED", "CANCELLED", "STOPPED"}),
    "WAITING_APPROVAL": frozenset({"WAITING_APPROVAL", "EXECUTING", "REPLANNING", "BLOCKED", "CANCELLED", "STOPPED"}),
    **{status: frozenset({status}) for status in TERMINAL_GOAL_STATUSES},
}
