from __future__ import annotations

from aitest_runtime.durable_core import RuntimeError


class R42Error(RuntimeError):
    """Fail-closed R4.2 contract, replay, and boundary error."""


NOT_FOUND = "NOT_FOUND"
CONFLICT = "CONFLICT"
DUPLICATE = "DUPLICATE"
IDEMPOTENT_REPLAY = "IDEMPOTENT_REPLAY"
INVALID_TRIGGER = "INVALID_TRIGGER"
TRIGGER_SOURCE_CONFLICT = "TRIGGER_SOURCE_CONFLICT"
SOURCE_STALE = "SOURCE_STALE"
SOURCE_UNAVAILABLE = "SOURCE_UNAVAILABLE"
IMPACT_INPUT_INVALID = "IMPACT_INPUT_INVALID"
IMPACT_INCONCLUSIVE = "IMPACT_INCONCLUSIVE"
SELECTION_REVISION_CONFLICT = "SELECTION_REVISION_CONFLICT"
R2_BRIDGE_REJECTED = "R2_BRIDGE_REJECTED"
R2_BRIDGE_UNAVAILABLE = "R2_BRIDGE_UNAVAILABLE"
R2_RESULT_CONFLICT = "R2_RESULT_CONFLICT"
ARCHITECTURE_BOUNDARY_VIOLATION = "ARCHITECTURE_BOUNDARY_VIOLATION"

# Internal names are deliberately namespaced when they can surface through the
# shared RuntimeService.  The public error vocabulary above remains stable.
R42_SCHEMA_INVALID = "R4_2_SCHEMA_INVALID"
R42_EVENT_INVALID = "R4_2_EVENT_INVALID"
R42_COMMAND_INVALID = "R4_2_COMMAND_INVALID"
R42_MISSION_INVALID = "R4_2_MISSION_INVALID"
R42_REFERENCE_INVALID = "R4_2_REFERENCE_INVALID"
R42_IDENTITY_CONFLICT = "R4_2_IDENTITY_CONFLICT"
R42_IMMUTABLE_CONFLICT = "R4_2_IMMUTABLE_CONFLICT"
R42_STATE_TRANSITION_INVALID = "R4_2_STATE_TRANSITION_INVALID"
R42_EVENT_NOT_OWNED = "R4_2_EVENT_NOT_OWNED"

