const state={projectId:null,view:"overview",data:null};
const $=s=>document.querySelector(s);
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const badge=s=>{const v=String(s||"UNKNOWN");const c=/PASS|READY|COMPLETE|CLOSED|VERIFIED|APPROVE/.test(v)?"ok":/FAIL|BLOCK|REJECT|ABORT|REOPEN/.test(v)?"bad":"warn";return `<span class="badge ${c}">${esc(v)}</span>`};
async function api(url,opts){const r=await fetch(url,opts);const j=await r.json();if(!r.ok)throw new Error(j.message||j.error||r.statusText);return j}
async function boot(){try{await api('/api/health');$('#healthDot').className='dot ok';$('#healthText').textContent='Runtime 已连接';const p=await api('/api/projects');const sel=$('#projectSelect');sel.innerHTML=(p.projects||[]).map(x=>`<option value="${esc(x.project_id)}">${esc(x.name)} · ${esc(x.profile)}</option>`).join('');if(p.projects?.length){state.projectId=sel.value;await refresh()}else{showNotice('尚未创建项目。请先运行 INSTALL-AITEST.cmd，随后在 OpenCode 输入 /aitest-start，或使用 aitest project-init。');renderEmpty('等待创建第一个项目')}}catch(e){$('#healthDot').className='dot bad';$('#healthText').textContent='Runtime 未连接';showNotice(`无法连接本地控制面：${e.message}`);renderEmpty('请启动 start-control-plane.cmd')}}
function showNotice(t){const n=$('#notice');n.textContent=t;n.classList.remove('hidden')}function hideNotice(){$('#notice').classList.add('hidden')}
async function refresh(){if(!state.projectId)return;hideNotice();try{state.data=await api(`/api/report?project_id=${encodeURIComponent(state.projectId)}`);render()}catch(e){showNotice(e.message)}}
function metric(label,value,hint=''){return `<div class="card metric"><div class="label">${label}</div><div class="value">${value}</div><div class="hint">${hint}</div></div>`}
function actionButton(action,id,label,disabled=false){return `<button class="mini-action" data-action="${esc(action)}" data-id="${esc(id)}" ${disabled?'disabled':''}>${esc(label)}</button>`}
function table(cols,rows){if(!rows?.length)return `<div class="table-wrap"><div class="empty">暂无数据</div></div>`;return `<div class="table-wrap"><table><thead><tr>${cols.map(c=>`<th>${c[0]}</th>`).join('')}</tr></thead><tbody>${rows.map(r=>`<tr>${cols.map(c=>`<td>${typeof c[1]==='function'?c[1](r):esc(r[c[1]])}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
function render(){const d=state.data||{};const map={overview:['研发质量总览','Mission、人工任务、缺陷与质量调度统一状态面板'],missions:['Missions','状态机、执行游标与 Worker 会话'],human:['待我处理','登录、MFA、Showcase、评审与人工接管'],defects:['缺陷生命周期','L1–L7 Observation 聚合、确认、修复与复测'],campaigns:['L1–L7 调度','需求 Campaign 与版本 Campaign'],connectors:['连接器','Current Release、CAT、DB、部署与浏览器能力']};[$('#title').textContent,$('#subtitle').textContent]=map[state.view];const fn={overview:overview,missions:missions,human:humanView,defects:defectsView,campaigns:campaignsView,connectors:connectorsView}[state.view];$('#content').innerHTML=fn(d)}
function overview(d){const p=d.project||{},mc=d.mission_counts||{},dc=d.defect_counts||{},hc=d.human_task_counts||{};return `<div class="grid">${metric('活跃 Missions',(d.missions||[]).filter(x=>!['COMPLETED','ABORTED'].includes(x.state)).length,'继续测试会恢复持久化游标')}${metric('待人工处理',(hc.WAITING||0)+(hc.CLAIMED||0),'授权、登录、Showcase、业务判断')}${metric('开放缺陷',(d.defects||[]).filter(x=>!['CLOSED','NOT_A_DEFECT','DUPLICATE'].includes(x.status)).length,'按同根因聚合 L1–L7 Observation')}${metric('质量 Campaign',(d.campaigns||[]).length,'Requirement / Release 两类调度')}</div><div class="split section"><div><div class="section-head"><h2>最近 Missions</h2></div>${missionTable(d.missions?.slice(0,8))}</div><div><div class="section-head"><h2>项目状态</h2></div><div class="card"><dl class="kv"><dt>项目</dt><dd>${esc(p.project?.name||p.name||state.projectId)}</dd><dt>Profile</dt><dd>${esc(p.project?.profile||'GENERIC')}</dd><dt>代码仓</dt><dd>${esc(p.repositories??0)}</dd><dt>环境</dt><dd>${esc(p.environments??0)}</dd><dt>连接器</dt><dd>${esc(p.connectors??0)}</dd><dt>版本</dt><dd>${esc(p.releases??0)}</dd><dt>需求</dt><dd>${esc(p.requirements??0)}</dd></dl></div></div><div class="section"><div class="section-head"><h2>开放缺陷</h2></div>${defectTable(d.defects?.slice(0,8))}</div>`}
function missionTable(rows){return table([['Mission','title'],['状态',r=>badge(r.state)],['需求','requirement_id'],['游标',r=>esc(r.current_step_id||'—')],['计划',r=>`v${esc(r.plan_version)}`],['操作',r=>actionButton('mission-continue',r.mission_id,'继续/恢复',['COMPLETED','ABORTED'].includes(r.state))]],rows)}
function missions(d){return missionTable(d.missions)}
function humanActions(r){const closed=!['WAITING','CLAIMED'].includes(r.status);return [r.status==='WAITING'?actionButton('human-claim',r.human_task_id,'领取'):'' ,actionButton('human-browser',r.human_task_id,'打开受控浏览器',closed),actionButton('human-complete',r.human_task_id,'完成并继续',closed)].join(' ')}
function humanView(d){return table([['任务','title'],['类型',r=>badge(r.task_type)],['状态',r=>badge(r.status)],['请求动作','requested_action'],['处理人','assigned_to'],['Mission','mission_id'],['操作',humanActions]],d.human_tasks)}
function defectTable(rows){return table([['缺陷','title'],['状态',r=>badge(r.status)],['严重度',r=>badge(r.severity)],['首次层','first_detected_layer'],['涉及层',r=>esc(r.detected_layers?.join?.(' / ')||r.detected_layers_json||'—')],['责任 SST','primary_sst_id']],rows)}
function defectsView(d){return defectTable(d.defects)}
function campaignsView(d){return table([['Campaign','title'],['类型',r=>badge(r.campaign_type)],['状态',r=>badge(r.status)],['版本','release_id'],['需求','requirement_id'],['更新时间','updated_at']],d.campaigns)}
async function connectorsView(d){setTimeout(async()=>{try{const j=await api(`/api/connectors?project_id=${encodeURIComponent(state.projectId)}`);$('#connectorTable').innerHTML=table([['连接器','name'],['类型',r=>badge(r.kind)],['状态',r=>badge(r.status)],['Adapter','adapter_path'],['上次检查','last_checked_at'],['错误','last_error']],j.connectors)}catch(e){}},0);return `<div id="connectorTable"><div class="card">正在加载连接器…</div></div>`}
function renderEmpty(t){$('#content').innerHTML=`<div class="card empty">${esc(t)}</div>`}
async function runAction(action,id){
  if(action==='mission-continue'){await api(`/api/missions/${encodeURIComponent(id)}/continue`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({actor:'local-user'})})}
  if(action==='human-claim'){await api(`/api/human-tasks/${encodeURIComponent(id)}/claim`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({user_id:'local-user'})})}
  if(action==='human-complete'){const comment=window.prompt('补充处理说明（不要填写密码、Token、Cookie）','已完成')||'';await api(`/api/human-tasks/${encodeURIComponent(id)}/complete`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({user_id:'local-user',comment,evidence:[]})})}
  if(action==='human-browser'){
    const start=window.prompt('受控浏览器起始地址（必须属于已批准测试环境）','')||'';
    if(!start)return;
    let domains=[];try{domains=[new URL(start).hostname]}catch{throw new Error('起始地址无效')}
    await api(`/api/human-tasks/${encodeURIComponent(id)}/open-browser`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({start_url:start,allowed_domains:domains})})
  }
  await refresh()
}
document.addEventListener('click',async e=>{const action=e.target.closest('[data-action]');if(action){action.disabled=true;try{await runAction(action.dataset.action,action.dataset.id)}catch(err){showNotice(err.message)}finally{action.disabled=false}return}const b=e.target.closest('nav button');if(b){document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');state.view=b.dataset.view;render()}});$('#projectSelect').addEventListener('change',e=>{state.projectId=e.target.value;refresh()});$('#refreshBtn').addEventListener('click',refresh);boot();
