"""R2.2 Mission Intake & Scope Orchestration V1."""

from .contracts import (
    CONTRACT_VERSION,
    GoalDefinitionV1,
    CREATE,
    EXPLICIT_SET,
    GOAL_DEFINITION_CONTRACT_VERSION,
    GOAL_DEFINITION_SCHEMA_VERSION,
    IdempotencyConflict,
    MISSION_INTAKE_CONTRACT_VERSION,
    MissionIntakeError,
    MissionIntakeRequest,
    MissionIntakeRequestV1,
    OP_CREATE,
    OP_REVISE,
    OPERATIONS,
    REVISE,
    SCHEMA_VERSION,
    SCOPE_MODE_EXPLICIT_SET,
    SCOPE_EXPLICIT_SET,
    SOURCE_KINDS,
    SourceDescriptor,
    OPERATION_CREATE,
    OPERATION_REVISE,
    R2_2_CONTRACT_VERSION,
    R2_2Error,
    GoalDefinition,
)
from .normalizer import build_goal_definition, build_resolution_request, normalize_and_build, normalize_request
from .orchestrator import (
    MissionIntakeOrchestrator,
    MissionIntakeApplicationService,
    MissionIntakeResult,
    MissionIntakeService,
    handle_mission_intake,
    intake_mission,
    orchestrate_mission_intake,
)

__all__ = [
    "CONTRACT_VERSION",
    "R2_2_CONTRACT_VERSION",
    "CREATE",
    "EXPLICIT_SET",
    "GOAL_DEFINITION_CONTRACT_VERSION",
    "GOAL_DEFINITION_SCHEMA_VERSION",
    "GoalDefinitionV1",
    "IdempotencyConflict",
    "MISSION_INTAKE_CONTRACT_VERSION",
    "MissionIntakeError",
    "MissionIntakeRequest",
    "MissionIntakeRequestV1",
    "OP_CREATE",
    "OP_REVISE",
    "OPERATION_CREATE",
    "OPERATION_REVISE",
    "OPERATIONS",
    "REVISE",
    "SCHEMA_VERSION",
    "SCOPE_MODE_EXPLICIT_SET",
    "SCOPE_EXPLICIT_SET",
    "SOURCE_KINDS",
    "SourceDescriptor",
    "R2_2Error",
    "GoalDefinition",
    "build_goal_definition",
    "build_resolution_request",
    "normalize_and_build",
    "normalize_request",
    "MissionIntakeOrchestrator",
    "MissionIntakeApplicationService",
    "MissionIntakeService",
    "MissionIntakeResult",
    "intake_mission",
    "handle_mission_intake",
    "orchestrate_mission_intake",
]
